# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'data4help' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for data4help
  
  pod 'Alamofire', '~> 4.3'
  pod 'SwiftyJSON', '~> 4.2'

  target 'data4helpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'data4helpUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
